/**
 * Turning a Custom Elements Manifest into this addon's event catalog.
 *
 * The `{ name, tags }[]` shape isn't arbitrary — it's a direct projection of a
 * CEM, inverted: a manifest is indexed by element ("what does this tag fire?"),
 * and the catalog is indexed by event ("which tags fire this name?"). That
 * inversion is the whole point, because it's what makes `shared` computable:
 * an event name reachable from more than one tag is precisely one a listener
 * bound on a common ancestor can't attribute without also reading the origin.
 *
 * Kept free of `node:fs` so it stays a pure function over parsed JSON, and can
 * be tested without touching a disk.
 */
import type { EventCatalogEntry } from '../core/types';

/**
 * The slice of the CEM schema this actually reads. Deliberately loose — a
 * manifest is generated by any of several tools at varying schema versions,
 * and anything with `tagName` and `events` is usable regardless of what else
 * it carries.
 */
interface ManifestDeclaration {
  readonly tagName?: string;
  readonly events?: readonly { readonly name?: string }[];
}

interface ManifestModule {
  readonly declarations?: readonly ManifestDeclaration[];
}

export interface CustomElementsManifest {
  readonly modules?: readonly ManifestModule[];
}

/** Thrown with a message meant to be shown to a person, not a stack trace. */
export class ManifestError extends Error {
  override name = 'ManifestError';
}

export function catalogFromManifest(manifest: unknown): EventCatalogEntry[] {
  if (typeof manifest !== 'object' || manifest === null) {
    throw new ManifestError('Manifest is not a JSON object.');
  }
  const { modules } = manifest as CustomElementsManifest;
  if (!Array.isArray(modules)) {
    throw new ManifestError('Manifest has no `modules` array — is this actually a custom-elements.json?');
  }

  const byName = new Map<string, Set<string>>();

  for (const module of modules) {
    for (const declaration of module?.declarations ?? []) {
      // Only element declarations matter: a module also carries plain classes,
      // variables and functions, none of which can dispatch from a tag.
      if (!declaration?.tagName) continue;
      for (const event of declaration.events ?? []) {
        if (!event?.name) continue;
        let tags = byName.get(event.name);
        if (!tags) byName.set(event.name, (tags = new Set()));
        tags.add(declaration.tagName);
      }
    }
  }

  // Sorted so regenerating an unchanged manifest produces a byte-identical
  // file — otherwise every rebuild churns the diff.
  return [...byName]
    .map(([name, tags]) => ({ name, tags: [...tags].sort() }))
    .sort((a, b) => a.name.localeCompare(b.name));
}
